---
- hosts: localhost
  vars:
    remote_user: vagrant
  vars_files:
    - vars.yml
  sudo: yes
  user: root
  connection: local
  gather_facts: False
  roles:
  - { role: rvm_io.rvm1-ruby, tags: ruby, sudo: True }
  tasks:
  - name: update apt cache
    apt: update_cache=yes
  - name: Install required system packages.
    apt: pkg={{ item }} state=installed 
    sudo_user: root
    with_items: 
      - "{{ system_packages }}"
  - name: change permissions
    file: path=/opt owner={{ remote_user }} group={{ remote_user }} state=directory recurse=yes
  - name: change permissions
    file: path=/usr/local/rvm owner={{ remote_user }} group={{ remote_user }} state=directory recurse=yes 
  - name: add rvm to bashrc
    lineinfile: dest=/etc/bash.bashrc line="/usr/local/rvm/scripts/rvm"
  - name: reload bash.bashrc file
    command: "source /etc/bash.bashrc" 
  - name: install jekyll 
    command: "gem install jekyll"




