---
- hosts: localhost
  vars_files:
    - vars.yml
  sudo: yes
  user: root
  connection: local
  gather_facts: False
  roles:
  - { role: rvm_io.rvm1-ruby, tags: ruby, sudo: True }
  tasks:
  - name: update apt cache
    apt: update_cache=yes
  - name: Install required system packages.
    apt: pkg={{ item }} state=installed 
    sudo_user: root
    with_items: 
      - "{{ system_packages }}"
  - name: install jekyll 
    command: "gem install jekyll"




